Celsia.Esfera/Portal/Controllers/FileController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Security.Claims;
using Bussines;
using Bussines.Bussines;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Portal.ViewModels;
using Utilities.Cache;
using Utilities.Messages;

namespace Portal.Controllers
{
    [Authorize(Roles = "Administrador")]
    public class FileController : Controller
    {
        private readonly IPersonBussines personBussines;
        private readonly ICacheUtility cache;
        private readonly ILogger<FileController> logger;

        public FileController(EsferaContext context, ICacheUtility cache, ILogger<FileController> logger)
        {
            this.logger = logger;
            this.cache = cache;

            this.personBussines = new PersonBussines(context, this.cache);
        }

        // GET: File
        public ActionResult Index()
        {
            FileViewModel viewModel = new FileViewModel();

            return this.View(viewModel);
        }

        [HttpPost]
        public ActionResult Index(FileViewModel fileViewModel)
        {
            try
            {
                if (this.ModelState.IsValid)
                {
                    string userName = this.User.FindFirst(ClaimTypes.Name).Value;

                    string tempPath = Path.GetTempFileName();

                    using (FileStream stream = System.IO.File.Create(tempPath))
                    {
                        fileViewModel.UploadFile.CopyTo(stream);
                    }

                    List<ApplicationMessage> processMessages = this.personBussines.UploadVinculatedPersons(tempPath, userName);

                    fileViewModel.Messages = processMessages;
                    fileViewModel.TotalRows = processMessages.Count;        
                }
            }
            catch (Exception exec)
            {
                fileViewModel.UserMesage = new ApplicationMessage(this.cache, MessageCode.GeneralError);
                this.logger.LogError(exec, fileViewModel.UserMesage.Text);
            }

            return this.View(fileViewModel);
        }
    }
}

Celsia.Esfera/Portal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>@ViewData["Title"] - CELSIA</title>

    <link href="~/css/site.css" rel="stylesheet" />
    <link href="~/lib/dataTables/dist/css/dataTables.css" rel="stylesheet" />

    <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">
</head>
<body class="sb-nav-fixed">
    @using Microsoft.AspNetCore.Identity
    @using Entities.Models;

    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-orange">
        <a class="navbar-brand mr-4"><img src="~/img/logo.svg" /></a><button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#" title="Menu">
            <i class="fas fa-bars"></i>
        </button>
        <!-- Navbar Search-->
        <div class="d-none d-md-inline-block ml-auto mr-0 mr-md-3 my-2 my-md-0">

            @using System.Security.Claims

            <div class="user-info">
                <span>@User.FindFirst(ClaimTypes.Name).Value</span>
                <span><strong>@User.FindFirst(ClaimTypes.Role).Value</strong></span>
            </div>




        </div>
        <!-- Navbar-->
        <ul class="navbar-nav ml-auto ml-md-0">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                    <a class="dropdown-item" asp-controller="Login"  asp-action="Logout">Cerrar Sesión</a>
                </div>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">Clientes</div>
                        <a class="nav-link" asp-controller="Customer" asp-action="Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-search"></i></div>
                            Consultar clientes
                        </a>
                        @if (User.FindFirst(ClaimTypes.Role).Value == "Administrador")
                        {
                            <a class="nav-link" asp-controller="File" asp-action="Index">
                                <div class="sb-nav-link-icon"><i class="fas fa-upload"></i></div>
                                Carga masiva
                            </a>
                        }
                        <div class="sb-sidenav-menu-separator"></div>
                        <div class="sb-sidenav-menu-heading">No asociados</div>
                        <a class="nav-link" asp-controller="Person" asp-action="Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-user"></i></div>
                            Gestionar personas
                        </a>
                    </div>
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid">
                    @RenderBody()
                </div>
            </main>
            <footer class="py-4 mt-auto">
                <div class="container-fluid text-muted text-center small">
                    Copyright &copy; 2020. Todos los derechos reservados
                </div>
            </footer>
        </div>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/fontAwesome/dist/all.min.js"></script>
    <script src="~/lib/dataTables/dist/js/jquery.dataTables.min.js"></script>
    <script src="~/lib/dataTables/dist/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>